# Site settings
title: Weihnachtsmarkt Münster Rathaus
email: muenster@codefor.de
description: > # this means to ignore newlines until "baseurl:"
  Die Weihnachtsmarkt App für den münsteraner Weihnachtsmarkt am Rathaus.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codeformuenster.org/weihnachtsmarkt" # the base hostname & protocol for your site
twitter_username: codeformuenster
github_username:  codeformuenster
permalink: /staende/:title

# Build settings
markdown: kramdown
sass:
  style: compressed
