version: '2'

services:
  weihnachtsmarkt:
    build: .
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      KINTO_URL: http://kinto:8888/v1
    # volumes:
    #   - .:/usr/src/app

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: weihnachtsmarkt
      POSTGRES_PASSWORD: PASSWORD

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  kinto:
    image: kinto/kinto-server:11.1.0
    ports:
      - 8888:8888
    volumes:
      - ./kinto/config:/etc/kinto
    depends_on:
      - postgres
      - elasticsearch
