version: '2'

services:
  weihnachtsmarkt:
    build: .
    ports:
      - "8000:8000"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_INDEX_PREFIX: "weihnachtsmarkt-"
    # volumes:
    #   - .:/usr/src/app

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  kinto:
    image: kinto/kinto-server:10.1.2
    # command: sh -c "kinto migrate --ini /etc/kinto/kinto.ini && kinto start --ini /etc/kinto/kinto.ini --port 8888"
    links:
      - postgres
    ports:
      - "8888:8888"
    environment:
      # FIXME move to config/kinto.ini
      KINTO_CACHE_BACKEND: kinto.core.cache.postgresql
      KINTO_CACHE_URL: postgres://postgres:postgres@postgres/postgres
      KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
      KINTO_STORAGE_URL: postgres://postgres:postgres@postgres/postgres
      KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
      KINTO_PERMISSION_URL: postgres://postgres:postgres@postgres/postgres
    volumes:
      - ./kinto/config:/etc/kinto
