version: '2'

services:
  app:
    build: .
    command: python ./test1.py
    environment:
      KINTO_URL: https://kinto.codeformuenster.org/v1
      KINTO_USER: admin
      KINTO_PASSWORD: 
    volumes:
      - .:/usr/src/app
